# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.aws_key_id }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.aws_access_key }}
        export AWS_DEFAULT_REGION="eu-west-2"
        cd ecr
        terraform -v
        terraform init
        terraform fmt
        terraform plan
